# Generated by Django 3.2.16 on 2023-06-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230609_0114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='self_subscription_restrict',
        ),
    ]
